before_install:
  - source ./.byond-version.sh
  - sudo apt-get update -qq
  - sudo apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386 -qq

install:
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - sudo make install
  - cd ..

script:
  - DreamMaker baystation12.dme
